### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by Daniel-GIT117** [OpenKNX/Kaenx-Creator#44]
I'm having issues with de KNXPROD files after they have been created or edited with Kaenx-Creator. If I open an existing working KNXPROD with Kaenx-Creator change nothing and then "publish" it to a new file the issue occurs.

I think that there is probably a variable in the code with the same name or ID, but I'm unable to find it.

Import of the KNXPROD file goes without on issue but when I try to embed the devices in a RF-coupler the issue occurs. 

************** Exception Text **************
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at TR131_mc.DeviceWithKeyedParams..ctor(IDevice device)
   at TR131_mc.HomeForm.OnLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by thewhobox** [comment]
Could you please provide me the ae-manu and original knxprodfile?

This sounds like a duplicate in the dynamic part.
Maybe a ParameterSeparator or ChannelId.

**Comment by Daniel-GIT117** [comment]
Hi Mike,

Thx for your quick reply.

I have uploaded "MDT-RF-AKK02UP01.zip" with 4 files.

1. The original KNXPROD "MDT-RF-AKK02UP01.knxprod"
2. The corresponding ae-manu file "MDT-RF-AKK02UP01.ae-manu"

When creating a KNXPROD file based on the MDT-RF-AKK02UP01.ae.manu the issue occurs.

The file "Costum-MDT-RF-AKK02UP01.ae-manu" I have addited the media type from RF to TP because my Hager Media Coupler Line is a TP line. So the device must be a TP device.

I have done this by editing the "MaskId": "MV-2705" to "MaskId": "MV-0705" 

The file "Costum-MDT-RF-AKK02UP01.knxprod" is based on the "Costum-MDT-RF-AKK02UP01.ae-manu"

[Costum-MDT-RF-AKK02UP01.zip](https://github.com/user-attachments/files/16613409/Costum-MDT-RF-AKK02UP01.zip)

**Comment by thewhobox** [comment]
I think this does not work as you expect...

You cant just change MaskVersion and everything is fine.
There are a lot of options which depend on it.
Most the LoadProzedur.
Also this is not "change nothing and then publish".

If the Line for RF ist a MediaType TP, this is completetly wrong.
Please contact the manufacturer of your Media Coupler.

**Comment by Daniel-GIT117** [comment]
Hi Mike,

Thx for you reply. The Hager RF line must be configured as an TP line. The documentation also states that. I have many components in it.

The problem is that I bought a RF devices which has of course the media type RF. I was looking for a way to fix this. I think that it could work with tweaking the knxprod and the parameters. But I keep running into this issue, yesterday I was convinced that it had to do with the creation of the knxprod with Kaenx-Creation. But maybe the error is on my side.

If you have any ideas any would be much appreciated.
